NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.developers.workspace-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.developers.workspace-cert.pem
    OrganizationalUnitIdentifier: peer
